<a href="https://www.kaggle.com/code/soumikniloy/a-million-news-headline?scriptVersionId=134944809" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM

/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tenso

In [2]:
# Load the dataset
df = pd.read_csv('/kaggle/input/million-headlines/abcnews-date-text.csv')

In [3]:
# Preprocessing
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['headline_text'])
vocab_size = len(tokenizer.word_index) + 1

In [4]:
# Convert text to sequences
sequences = tokenizer.texts_to_sequences(df['headline_text'])

In [5]:
# Pad sequences
max_len = max(len(seq) for seq in sequences)
sequences = pad_sequences(sequences, maxlen=max_len)

In [6]:
# Split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(sequences, df['publish_date'], test_size=0.2, random_state=42)

In [7]:
# Build the RNN model
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=100, input_length=max_len))
model.add(LSTM(units=64))
model.add(Dense(units=1))

In [8]:
# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

In [9]:
# Train the model
model.fit(X_train, y_train, batch_size=64, epochs=10)

Epoch 1/10
15553/15553 [==============================] - 3307s 212ms/step - loss: 404401604788224.0000
Epoch 2/10
15553/15553 [==============================] - 3347s 215ms/step - loss: 404358889996288.0000
Epoch 3/10
15553/15553 [==============================] - 3372s 217ms/step - loss: 404319094439936.0000
Epoch 4/10
15553/15553 [==============================] - 3388s 218ms/step - loss: 404279064002560.0000
Epoch 5/10
15553/15553 [==============================] - 3360s 216ms/step - loss: 404237657833472.0000
Epoch 6/10
15553/15553 [==============================] - 3362s 216ms/step - loss: 404198634029056.0000
Epoch 7/10
15553/15553 [==============================] - 3383s 218ms/step - loss: 404156087009280.0000
Epoch 8/10
15553/15553 [==============================] - 3363s 216ms/step - loss: 404117230977024.0000
Epoch 9/10
15553/15553 [==============================] - 3346s 215ms/step - loss: 404076864995328.0000
Epoch 10/10
15553/15553 [==============================] - 3337s

In [10]:
# Evaluate the model on the test set
loss = model.evaluate(X_test, y_test)
print('Test Loss:', loss)

7777/7777 [==============================] - 37s 5ms/step - loss: 404019822460928.0000
Test Loss: 404019822460928.0


In [11]:
# Make predictions on the test set
predictions = model.predict(X_test)

7777/7777 [==============================] - 36s 5ms/step


In [12]:
# Convert predictions to binary values
predictions_binary = [1 if pred >= 0.5 else 0 for pred in predictions]

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [14]:
#confusion matrix
cm = confusion_matrix(y_test, predictions_binary)
print(cm)

[[ 0  0  0 ...  0  0  0]
 [34  0  0 ...  0  0  0]
 [45  0  0 ...  0  0  0]
 ...
 [ 5  0  0 ...  0  0  0]
 [ 8  0  0 ...  0  0  0]
 [ 7  0  0 ...  0  0  0]]
